### ISSUE TITLE
Storage areas disappearing in factory sectors

### ISSUE THREAD

**Issue by DjHaski** [KillahPotatoes/KP-Liberation#645] opened 2019-07-29 13:01 UTC
### Basic Information
**Mission version:** v0.96.5
**Map used:** Takistan
**Mods used:**
- ACE
- RHSAFRF
- RHSUSAF
- Project OPFOR
- MCC Sandbox 4
- Achilles
- CUP (Core, Maps, CWA)
- Ace Compat (AFRF + USAF)
- JSRS Soundmod (AFRF, USAF)
- Blastcore

**Dedicated or local game:** Local

**Source of the mission file (URL):** Workshop

### Individual Things
**Did you edit anything within the mission files?**
No

### Short Issue Description
Storage areas disappearing in all factory sectors when you relog in mission. You can build storage area again, but it will be empty.

### Expected Behaviour
Storage areas should not disappear.

### Steps to Reproduce the Issue
Just relog in mission.

**Comment by domse167** [comment] 2019-07-30 20:16
Hey lad,

Wyqer and me weren't able to reproduce your issue at all. 
Maybe you can provide us some logs when playing your mission file, before relogging and one after placing, waiting around 15 minutes and relog again to see, why your crates are disapearing. Thanks for your help in advance!

**Comment by DjHaski** [comment] 2019-07-30 21:30
Updated mod list. I need to post logs located in `AppData/Local/Arma 3`?

**Comment by domse167** [comment] 2019-07-30 21:32
Regarding to your updated modlist, i will test this issue tomorrow again. Will tell you by then which logfiles you need to send us! Thank you for your help!

**Comment by domse167** [comment] 2019-07-31 11:20
Hey lad,

tested some stuff and found out that MCC is causing this issue. We are looking through the code if there might be a way around but it seems bad looking. So better don't use MCC anylonger, because its well known for causing issues around the Arma 3 main game.

**Comment by Eogos** [comment] 2019-08-09 00:42
Might be worth reopening this as I've seen several others, including people not running MCC, reporting storage areas disappearing in the Discord

**Comment by domse167** [comment] 2019-08-09 00:54
Opened this up again for further investigation.

**Comment by GitHubUser071016** [comment] 2019-08-09 02:12
### New Report of the Same Bug

### Basic Information

**Arma 3 version:** v1.94.145977 with all DLC including creator DLCS
**Mission version:** v0.96.5
**Map used:** song_bin_tanh
**Mods used:** unsung

**Full list of mods loaded in Arma 3:**

- CBA_A3
- CUP_Terrains_Core
- CUP_Terrains_Maps
- CUP_Terrains_CWA
- CUP_Units
- CUP_Vehicles
- CUP_Weapons
- unsung
- AlRayakV0044
- xCam_Taunus
- Jbad
- LYTHIUM
- panthera_a3 
- ProjectOPFOR
- RHSAFRF
- RHSUSAF
- RHSGREF
- RHSSAF 
- bwa3
- AdvancedSlingLoading
- AdvancedTowing
- AdvancedRappelling
- Enhanced Movement
- WMO - Walkable Moving Objects

**Dedicated or local game:** Local

**Source of the mission file (URL):** Github

### Individual Things

**Did you edit anything within the mission files?**

In order to fix a known respawn huron bug of song_bin_tanh kp lib map which is caused by a model glitch of CH-21C chopper,

in the file

> \scripts\shared\functions\F_getMobileRespawns.sqf

in the line

> ((getpos _x) select 2) < 5 &&

number 5 has been modified to 6.

### Short Issue Description

Storage areas disappear in all factory sectors when you reload the mission.

### Expected Behaviour

Storage areas should not disappear.

### Steps to Reproduce the Issue

I ran the map as local host and saved the game, then later reloaded it and ran it further. This was **repeatedly done** more times when the bug has eventually occured.

**Comment by Wyqer** [comment] 2019-08-11 19:49
Fixed with https://github.com/KillahPotatoes/KP-Liberation/commit/1f353e3a80341dad51e91a5a19aa92dfe6140aca#diff-33efaffe0bbc56e3e30590e0cb9d40ab

**Closed by Wyqer** 2019-08-11 19:49 UTC
Labels: bug, done
