### ISSUE TITLE
Sidemissions for 0.97

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#672] opened 2019-09-27 20:14 UTC
With v0.97 there will be a lot more possibilities for sensible sidemissions, and this thread can be used to save ideas for new missions.
So if you've an idea for a mission you can just post it here.

The best way would be the following structure:
- Title
- Costs (supply, ammo, fuel, Intel) for sidemissions or trigger condition for event missions
- Description
- Reward

! A post in this thread is no guarantee, that the mission will be implemented !

**Comment by Eogos** [comment] 2019-09-27 20:36
**Civilian Relief Effort**

**Cost:** 400-800 Supply (More Supply used more civ rep gained?)

**Description:** Can only be selected when at negative civilian reputation and controls a City/Town sector. Upon selection a mission will be spawned to take an IDAP (or other relevant supply vehicle) to the City/Town and "distribute" the supplies, perhaps on arrival you begin doing various interactions that take a moment to complete that sets up a sort of air station or something. Civilians spawned just for this mission will show up requesting medical aid, food rations, water, etc. and the players need to give them the appropriate items/treat them. Players will also need to be on the look out for suspicious individuals as freedom fighters may try to attack the relief effort either outright or via bombing. 

**Reward:** Medium gain in civ rep if relief effort happens with no incident or a small gain if an attack happens.

**Comment by Eogos** [comment] 2019-09-27 20:44
**Probing Attack/Feint Assault**

**Cost:** 20 intel

**Description:** Begin a "fake" attack on a sector meant to drawn enemy forces into the battle and away from other sectors nearby. Objective would be either a destruction of a certain % of the sector garrison (10-25% perhaps) or the targeting of certain officers or other important objectives in the sector (spawned specifically for this mission). Friendly AI with their own objectives or just meant to assist could be pre-spawned for the mission as well for an addition resource cost perhaps.

**Reward:** If successful the enemy commander will have become panicked enough to hastily divert troops from other nearby garrisons to reinforce the sector rather than call for reinforcements proper as that would take longer. For a period of time, all sectors within a certain radius to the "probed" sector would have their garrisons reduced by a % but will return to full strength after a time, as well the probed sector will keep it's now increased garrison from the reinforcements until damaged from an attack or outright captured.

**Comment by Eogos** [comment] 2019-09-27 20:56
**Resistance Vehicle Requests**

**Cost:** None outside of the cost to build a vehicle to give away. Mission would trigger at random so long as player side has above 75% civil reputation.

**Description:** The Resistance is gaining momentum and is now requesting additional aid in the form of vehicle assets. To complete the mission the players will need to purchase and deliver an armed vehicle of their choice to the resistance (or pre-spawned from a selection of vehicles defined in the preset if the build menu way is to open ended and allows for too many weird issues). Once at the meet up there is a chance for the enemy side to ambush the resistance and players, if this happens then the players must defend the resistance fighters (who should be confined to a certain area of the meet up zone or just have their pathing disabled to prevent frustration). Only two of the Resistance fighters need to survive the ambush.

**Reward/Penalty:** If successful the vehicle provided then spawns with a resistance crew for all guerillas operations in addition to the already random spawned resistance forces (and possibly vehicles) for a limited amount of times or until the vehicle is destroyed in fighting, whichever comes first. If the players fail to protect the resistance fighters in the event of an ambush then the vehicle will be lost and they will suffer a very small civ rep penalty.

**Comment by Pi123263** [comment] 2019-09-27 20:58
**Supply Depot Attack**

**Cost:** 15 Intel

**Description:** The players have to attack an enemy supply depot thats storing supplies/fuel/ammo crates or also more 'themed' things like spare parts (which could possibly also give resources if brought back to base).

**Reward:** If the supplies are captured/destroyed succesfully the chance of a vehicle of the category (wheeled/tracked/helicopter/...) will be reduced by 20-40% for a limited amount of time.

**Sidenote:** One problem with this suggestion is (as pointed out by Eogos in the Discord) that it could turn into the same situation as the FOB hunt where the target just gets shot at with artillery, which doesnt really add much to the mission.

**Comment by Eogos** [comment] 2019-09-27 21:05
**Imminent Attack Warning**

**Cost:** 5 intel, 100 supply

**Description:** The players choose an enemy held City/Town sector to warn of an imminent attack via drones dropping flyers over the sector. 

**Reward/Penalty:** Once completed, civilian presence in the town will be reduced by 25% for a period of time and and additional bonus of civ rep will be gained upon capture of the town for warning the civilians ahead of time so long as the presence in the town is still reduced on sector activation. However, due to the warning flyers, if the players do not attack that town in a timely manner then it's garrison will be increased by the enemy commander. The sector will also be able to call for reinforcements more quickly than normal for a period of time afterwords.

**Comment by Eogos** [comment] 2019-09-27 21:15
**Mine Clearing**

**Cost:** None, mission is spawned at random. Perhaps require enemy alert level to be above a certain % to activate.

**Description:** A randomly generated minefield is spawned (preferably near the "frontline") and the players are needed to clear it.

**Reward/Penalty:** If the players clear the minefield then they gain a small civilian reputation boost and a crate of Ammunition resources (to simulate gathering up all the explosives). If the players ignore the minefield three things can happen: 60% chance civilians wounded by the minefield causing medium civilian reputation drop, 30% chance civilians killed by the minefield causing large civilian reputation drop, 10% chance someone else manages to clear/mark the minefield and no one is hurt resulting in no gain or loss in civilian reputation.

**Sidenote:** This mission is meant to be more a distraction for the players, something they decide is something they need to deal with or not. In my opinion more random events/side missions like this are needed in order to shake up the "meta" of Liberation and prevent every campaign from being the same strategy over and over once a community gets good enough at Liberation. Of course this means that maybe this mission and any others like it, if added, should be enabled via a parameter instead so that those using Liberation as a basis for Zeus controlled events and what not don't have to deal with them if they don't want to.

**Comment by FunFact216** [comment] 2019-09-27 22:07
**Deep Strike**
**Cost:** 200 Supply, 50 Fuel, 10 Intel
**Description:** A helicopter is spawned with a small special forces team. Randomly, a distant garrison is targeted. An objective like HVT capture, prisoner rescue, resource raiding, or data recovery would be waiting there.
**Reward:** Mission dependent. HVT’s give intel, large stocks of resources, prisoners give supply/turned into random units, data recovery would give immediate intel.

**Note:** This would be a great way to get a safe foothold elsewhere on a map, or risk some extra supply for a chance to get something worth more than the cost.

**Comment by Eogos** [comment] 2019-09-27 22:17
> prisoners give supply/turned into random units

This could actually work nicely for the new garrison system in 0.97 as it would give the commander free units to assigns as a part of a sector garrison.

**Comment by LuizBarros99** [comment] 2019-09-27 22:18
I would like to add a bit of a "side objective" to the "FOB Hunting" mission. (or another more efficient way of acomplishing it) My suggestion basically

**FOB Hunting**

**COST**
Current cost, maybe add a minimum alert level of ~20-40%. (not to be changed, but for one additional outcome, player will need to have at least positive 5% Civilian Reputation)

**REWARD/PENALTY**
The players get two options to complete the already familiar FOB HUNTING mission. The known "destroy everything" option, and a NEW option to basically "steal everything".
The first option is basically the current option of having the enemy assets destroyed, and get a reduction to their Alert Level.

The other "new option", still adds a reduction to their alert level, AND the player gets to keep the vehicles, and whatever other kind of assets. ( if all the enemy assets are stolen, then maybe proportionally lower the reduction down to "only 30-35%" reduction from the current 40% reduction, since the player is also getting the vehicles as reward)

**SIDENOTE**
To make this a little more different from just an "expensive CONVOY-AMBUSH with no convoy but a base" mission, the enemy forces designed to defend this objective would need to be really a lot strongger than they currently are. This is to basically have it as if you really were going after somewhere important for the enemy's logistic.

 I would suggest to MAYBE even add separate variables to store the classnames of the enemies that are to defend those FOBs, as they would REALLY need to be a though nut to crack (Maybe this could allow for the CSAT Vipers to be introduced without having them be a "normal average infantryman or militia/military police guy"!) This could go as far as having a few "dedicated AA/SAM sites" spreaded AROUND the objective area + have have a bit more of enemy patrols around the objective are. 

(Around the objective area = INSIDE the area where we search after the FOB **AND ALSO** the areas AROUND this "search area", but with a little reduced intensity of enemy presence on the outside of the search area)

**How this could be implemented**
This could be implemented by assigning a variable to keep track of the "vehicle/asset state" and also creating triggers on the FOBs on the start of this side mission.

 Those triggers they would detect any assets within the "FOB range". Once activated (by having the assets within the "FOB range"), the trigger would basically make the variable for the given vehicle return true. If the vehicle is for some reason taken out the trigger area WHILE being "not dead", then it will be changed to false.
If said vehicle is destroyed, the variable will also be changed to return true, but since it is destroyed we don't need to worry about it anymore.

Then there would need to have something basically count the number of "trues" and divide it by the number of total assets. After it is done it would need to compare the resulting value to the value set on the "minimum objective impact" variable, that can be set on the config file.

Sorry for the wall of text, but I'd personally rather be overly detailed than underdetailed.

**Comment by LuizBarros99** [comment] 2019-09-27 22:20
> I would like to add a bit of a "side objective" to the "FOB Hunting" mission. (or another more efficient way of acomplishing it) My suggestion basically
> 
> **FOB Hunting**
> 
> **COST**
> Current cost, maybe add a minimum alert level of ~20-40%. (not to be changed, but for one additional outcome, player will need to have at least positive 5% Civilian Reputation)
> 
> **REWARD/PENALTY**
> The players get two options to complete the already familiar FOB HUNTING mission. The known "destroy everything" option, and a NEW option to basically "steal everything".
> The first option is basically the current option of having the enemy assets destroyed, and get a reduction to their Alert Level.
> 
> The other "new option", still adds a reduction to their alert level, AND the player gets to keep the vehicles, and whatever other kind of assets. ( if all the enemy assets are stolen, then maybe proportionally lower the reduction down to "only 30-35%" reduction from the current 40% reduction, since the player is also getting the vehicles as reward)
> 
> **SIDENOTE**
> To make this a little more different from just an "expensive CONVOY-AMBUSH with no convoy but a base" mission, the enemy forces designed to defend this objective would need to be really a lot strongger than they currently are. This is to basically have it as if you really were going after somewhere important for the enemy's logistic.
> 
> I would suggest to MAYBE even add separate variables to store the classnames of the enemies that are to defend those FOBs, as they would REALLY need to be a though nut to crack (Maybe this could allow for the CSAT Vipers to be introduced without having them be a "normal average infantryman or militia/military police guy"!) This could go as far as having a few "dedicated AA/SAM sites" spreaded AROUND the objective area + have have a bit more of enemy patrols around the objective are.
> 
> (Around the objective area = INSIDE the area where we search after the FOB **AND ALSO** the areas AROUND this "search area", but with a little reduced intensity of enemy presence on the outside of the search area)
> 
> **How this could be implemented**
> This could be implemented by assigning a variable to keep track of the "vehicle/asset state" and also creating triggers on the FOBs on the start of this side mission.
> 
> Those triggers they would detect any assets within the "FOB range". Once activated (by having the assets within the "FOB range"), the trigger would basically make the variable for the given vehicle return true. If the vehicle is for some reason taken out the trigger area WHILE being "not dead", then it will be changed to false.
> If said vehicle is destroyed, the variable will also be changed to return true, but since it is destroyed we don't need to worry about it anymore.
> 
> Then there would need to have something basically count the number of "trues" and divide it by the number of total assets. After it is done it would need to compare the resulting value to the value set on the "minimum objective impact" variable, that can be set on the config file.
> 
> Sorry for the wall of text, but I'd personally rather be overly detailed than underdetailed.

Oh something that I forgot, if you have positive reputation with the civilians, maybe have an option to leave (portions of) what you stole from the OPFOR, in exchange for a pretty good boost in Civ Reputation

**Comment by Eogos** [comment] 2019-09-27 22:26
@LuizBarros99 I feel like a combination of the two would be better, needed the destruction of the Taru pods but allowing (possibly requiring) the theft of the supply trucks and armed vehicles. Mostly just because currently the FOB Hunting mission in it's current form is no risk all reward if you have an artillery piece and a spotter or even just someone good with a MAAWS.

**Comment by LuizBarros99** [comment] 2019-09-27 23:23
> Mostly just because currently the FOB Hunting mission in it's current form is no risk all reward if you have an artillery piece and a spotter or even just someone good with a MAAWS and a nice hill to sit on.

 _Cough Cough_  Vorona _Cough Cough_ ...

**Comment by Eogos** [comment] 2019-09-29 17:17
**Checkpoint Construction**

**Cost:** 600 Supply, 400 Ammo, 100 Fuel. Can only be started when below 25% civilian reputation and owns a factory sector.

**Description:** Upon start of the mission, supply trucks are spawned that the players must take to the point where the checkpoint will be setup on a road near, but not within, a factory sector. Once there the players will either have a simple interaction to just "setup the checkpoint" or if whoever makes this wants to they might setup some sort of multiple interactions or maybe let the players choose which checkpoint preset they'd like idk. The checkpoint will remain on the map for the rest of the campaign until destroyed or abandoned.

**Reward/Penalty:** If a checkpoint is setup then any convoys going to or from any factories within a certain radius (should be small enough that only one, maybe two, factories can be affected) will have a reduced chance of being attacked by enemy resistance fighters. Additionally, IED spawns within a similar radius will be reduced to simulate patrols from and around the checkpoint marking and disarming some. However, while at negative civilian reputation there is a random chance for a decently sized resistance force to attack the checkpoint (similar to a battlegroup attack a sector/FOB) and destroying it. Additionally, if there is no friendly sector within a 2km radius then the checkpoint will be "abandoned" as enemy pushes have caused it to become to far isolated and a dangerous position for the forces there.

**Comment by Pi123263** [comment] 2019-09-29 17:21
> which checkpoint preset they'd like idk.

That could possibly also be turned into a sort of upgrade feature where you have different checkpoint levels and each level makes the checkpoint stronger (as in better defenses (visually aswell) and more AI) and increases the effects.

**Comment by Eogos** [comment] 2019-09-29 17:24
> 
> 
> > which checkpoint preset they'd like idk.
> 
> That could possibly also be turned into a sort of upgrade feature where you have different checkpoint levels and each level makes the checkpoint stronger (as in better defenses (visually aswell) and more AI) and increases the effects.

I know you commented this before I did the edit but perhaps that could be worked into the garrison system as well. Assigning more troops means the checkpoint gets an upgrade when reach a certain amount?

**Comment by dmorchard** [comment] 2019-09-30 00:27
**Apprehension of downed enemy pilot(s)**

**Cost**: Free when a random reward is desired; some quantity of intel points when players wish to guarantee the "brutal commander" option described below.

**Description**:  Similar to original Liberation's pilot rescue mission, but available later in the game when there is less enemy-held territory.  The general vicinity of a crashed enemy aircraft will be indicated on the map and players will be given a fixed amount of time to locate and capture the pilot after which he is considered to have escaped and will be deleted and the side mission terminates.  Once captured the pilot follows the existing capture and interrogation mechanic, so the reward is only obtained if delivery to a FOB is accomplished.  There could be a chance that there are multiple survivors and even more rarely one of them is an HVT.

**Reward**:  Intel points proportional to the quantity and "value" of the captured enemies.  If the HVT is identified as a former brutal commander of the region then his capture or a confirmed kill could also improve Blufor's civilian reputation.

**Comment by Daefikio** [comment] 2019-10-13 07:43
**Help Rebels**
**Cost**: ammo and fuel
**Description**: Help to increase civilian rep with helping the locals out with outfitting them with better weapons. This can have a sliding increase to also give rebel more of effective way to help. (form basic bolt to more better assault weapons more armored cars, and better launchers)
**Reward**: increase  positive civilian rep
**Failing**: wasted resources due to meeting area is ambush and if rebels killed and or truck is destroy no rep changes

**Comment by Daefikio** [comment] 2019-10-13 07:51
****Note this more for those that just choose NOT to assist rebels (evil option)
**Locate Rebel encampment:**

**Cost**: Supply ammo fuel

**Description**: Locate Rebel encampment and destroy them. Will help reduce rebel counter attack players faction

**Reward**: Decrease in Rebel attacking 
**Fail**:  Decrease civilian rep and increase rebel attacking during next assault on a sector

**Comment by Daefikio** [comment] 2019-10-13 07:57
**Ask the Rebels**
**Cost**: Supply ammo fuel
**Description**: Trade resources for some intel point (this can be increased to lots to prevent and give random value back to prevent too much spamming)
**Reward**: intel points
**Fail**: wasted supply due to enemy spec ops unit killed rebels

**Closed** 2020-05-04 12:49 UTC
Labels: help wanted
